// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// match_state_loop
Rcpp::NumericVector match_state_loop(Rcpp::NumericMatrix mstate, Rcpp::NumericMatrix xstate);
RcppExport SEXP BoolTraineR_match_state_loop(SEXP mstateSEXP, SEXP xstateSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mstate(mstateSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type xstate(xstateSEXP);
    __result = Rcpp::wrap(match_state_loop(mstate, xstate));
    return __result;
END_RCPP
}
// rcpp_man_dist
Rcpp::NumericVector rcpp_man_dist(Rcpp::NumericMatrix x_df, Rcpp::NumericMatrix y_df);
RcppExport SEXP BoolTraineR_rcpp_man_dist(SEXP x_dfSEXP, SEXP y_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x_df(x_dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type y_df(y_dfSEXP);
    __result = Rcpp::wrap(rcpp_man_dist(x_df, y_df));
    return __result;
END_RCPP
}
// rcpp_ham_dist
Rcpp::NumericVector rcpp_ham_dist(Rcpp::LogicalMatrix x_df, Rcpp::LogicalMatrix y_df);
RcppExport SEXP BoolTraineR_rcpp_ham_dist(SEXP x_dfSEXP, SEXP y_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type x_df(x_dfSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalMatrix >::type y_df(y_dfSEXP);
    __result = Rcpp::wrap(rcpp_ham_dist(x_df, y_df));
    return __result;
END_RCPP
}
// rcpp_m_score
Rcpp::IntegerVector rcpp_m_score(Rcpp::IntegerMatrix x_df);
RcppExport SEXP BoolTraineR_rcpp_m_score(SEXP x_dfSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type x_df(x_dfSEXP);
    __result = Rcpp::wrap(rcpp_m_score(x_df));
    return __result;
END_RCPP
}
// rcpp_validate
Rcpp::NumericVector rcpp_validate(Rcpp::NumericMatrix inf_mat, Rcpp::NumericMatrix true_mat);
RcppExport SEXP BoolTraineR_rcpp_validate(SEXP inf_matSEXP, SEXP true_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type inf_mat(inf_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type true_mat(true_matSEXP);
    __result = Rcpp::wrap(rcpp_validate(inf_mat, true_mat));
    return __result;
END_RCPP
}
// rcpp_simulate
Rcpp::List rcpp_simulate(Rcpp::List bmodel, Rcpp::LogicalVector fstate, bool verbose);
RcppExport SEXP BoolTraineR_rcpp_simulate(SEXP bmodelSEXP, SEXP fstateSEXP, SEXP verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< Rcpp::List >::type bmodel(bmodelSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector >::type fstate(fstateSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    __result = Rcpp::wrap(rcpp_simulate(bmodel, fstate, verbose));
    return __result;
END_RCPP
}
