# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Find a match between two data frames.
#' 
#' @description
#' (&&&Not for public use&&&)This function finds a match between two df of states. Used in match_state(). Return an row index vector indicating which row of mstate matches the rows in xstate.
#' 
#' @param mstate data frame. It should be a state(row) x gene(column) df.
#' @param xstate data frame. It should be a state(row) x gene(column) df.
match_state_loop <- function(mstate, xstate) {
    .Call('BoolTraineR_match_state_loop', PACKAGE = 'BoolTraineR', mstate, xstate)
}

#' @title Calculating pairwise scores between model and data states.
#' 
#' @description
#' This function calculates the pairwise scores between each row of model and data states. The score is calculated using a custom binary distance measure.
#' 
#' @param x_df matrix. It should be numerical matrix of model states.
#' @param y_df matrix. It should be numerical matrix of data states.
rcpp_man_dist <- function(x_df, y_df) {
    .Call('BoolTraineR_rcpp_man_dist', PACKAGE = 'BoolTraineR', x_df, y_df)
}

#' @title Calculating Hamming pairwise scores between model and data states.
#' 
#' @description
#' This function calculates the pairwise scores between each row of model and data states. The score is calculated using a custom binary distance measure.
#' 
#' @param x_df matrix. It should be logical matrix of model states.
#' @param y_df matrix. It should be logical matrix of data states.
rcpp_ham_dist <- function(x_df, y_df) {
    .Call('BoolTraineR_rcpp_ham_dist', PACKAGE = 'BoolTraineR', x_df, y_df)
}

#' @title Inner core for m_score()
#' 
#' @description
#' This function takes in a df with columns ranked wrt each row, and try to assign each row to a unique column without repetition.
#' 
#' @param x_df matrix. Matrix with columns ranked wrt each row.
rcpp_m_score <- function(x_df) {
    .Call('BoolTraineR_rcpp_m_score', PACKAGE = 'BoolTraineR', x_df)
}

#' @title Calculating validation scores between two adjacency matrices
#' 
#' @description
#' This function calculates the validation scores between two adjacency matrices.
#' 
#' @param inf_mat matrix. It should be adjacency matrix of inferred network.
#' @param true_mat matrix. It should be adjacency matrix of true network.
rcpp_validate <- function(inf_mat, true_mat) {
    .Call('BoolTraineR_rcpp_validate', PACKAGE = 'BoolTraineR', inf_mat, true_mat)
}

#' @title Simulate a Boolean model.
#' 
#' @description
#' (&&&Not for public use&&&)This function simulates the Boolean model using an initial state. For use within simulate_model(). Returns a matrix of full asynchronous state space.
#' 
#' @param bmodel list. A list of 4 lists created by decreate_model().
#' @param fstate data frame. It must have been initialised by initialise_data(), and has gene names as column names. Must contain only 1 row.
#' @param verbose logical. Indicates whether to output progress.
rcpp_simulate <- function(bmodel, fstate, verbose = FALSE) {
    .Call('BoolTraineR_rcpp_simulate', PACKAGE = 'BoolTraineR', bmodel, fstate, verbose)
}

